[project]
name = "pdf-to-md-llm"
version = "0.1.0"
description = "Convert pdf files to markdown files using a LLM"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.46.0",
    "click>=8.3.0",
    "pymupdf>=1.26.4",
    "python-dotenv>=1.1.1",
]
